### ISSUE TITLE
How to move TlsStream<TcpStream> between methods?

### ISSUE THREAD

**Issue by SuanCaiYv** [monoio-rs/monoio-tls#6]
<img width="728" alt="image" src="https://github.com/monoio-rs/monoio-tls/assets/29744434/c710d824-23e9-4f91-8efc-1011a3f59e6e">

I have get a value from accept() method from server, but the returned type is monoio_rustls::server::TlsStream, which is private because:
<img width="560" alt="image" src="https://github.com/monoio-rs/monoio-tls/assets/29744434/32a86c0b-cdef-4779-b774-2e046816321f">

The server mod is private.
And I want to deal the stream in new method, which required a type of tlsstream, but the private mod limit this. Is there something wrong on the visibility of the mod?
<img width="574" alt="image" src="https://github.com/monoio-rs/monoio-tls/assets/29744434/12a7f33f-7ef3-41a2-999e-809e2ffcee75">

And here is what Tokio does on the mod.

**Comment by ihciah** [comment]
The TlsStream is exported by a pub type alias here https://github.com/monoio-rs/monoio-tls/blob/master/monoio-rustls/src/lib.rs#L22
The stream mod is not public, but the Stream inside it is, and it is exported as a type alias.

**Comment by SuanCaiYv** [comment]
Got that, thanks!
